[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[bdist_wheel]
universal = 1

[tool.yapfignore]
ignore_patterns = [
  "tmp/**/*.py"
]

[tool.yapf]
based_on_style = "yapf"
indent_width = 2
